// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGxn4VN1jE2S1IRpJobXw6SVH2NE0ESqE',
    appId: '1:316325976878:web:d4ec39073f3d559b14f8bf',
    messagingSenderId: '316325976878',
    projectId: 'a522-17670',
    authDomain: 'a522-17670.firebaseapp.com',
    storageBucket: 'a522-17670.appspot.com',
    measurementId: 'G-1EY15RL650',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM599_MgqDEfuvA_CQiP9PjtP-nis9_g8',
    appId: '1:316325976878:android:b8ee994004c416df14f8bf',
    messagingSenderId: '316325976878',
    projectId: 'a522-17670',
    storageBucket: 'a522-17670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Egzff9RN3ibnXdhqlaC7Zn1V91rz12s',
    appId: '1:316325976878:ios:75105a53c59a92d714f8bf',
    messagingSenderId: '316325976878',
    projectId: 'a522-17670',
    storageBucket: 'a522-17670.appspot.com',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Egzff9RN3ibnXdhqlaC7Zn1V91rz12s',
    appId: '1:316325976878:ios:650fea3993199e4114f8bf',
    messagingSenderId: '316325976878',
    projectId: 'a522-17670',
    storageBucket: 'a522-17670.appspot.com',
    iosBundleId: 'com.example.a.RunnerTests',
  );
}
